# Generated by Django 5.1.6 on 2025-04-10 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("payments", "0001_initial"),
        ("rentals", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="rental",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="rentals.rental"
            ),
        ),
    ]
