# Generated by Django 5.1.6 on 2025-04-10 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("bicycles", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Rental",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rent_time", models.DateTimeField(auto_now_add=True)),
                ("return_time", models.DateTimeField(blank=True, null=True)),
                ("is_returned", models.BooleanField(default=False)),
                (
                    "bicycle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bicycles.bicycle",
                    ),
                ),
            ],
        ),
    ]
